### ISSUE TITLE
[Bug]: Cannot import `vue-chartjs`

### ISSUE THREAD

**Issue by avi12** [apertureless/vue-chartjs#985] opened 2022-12-23 22:18 UTC
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I'm trying to import `vue-chartjs` on a Vue 2 project (2.7.14) via PNPM, yet it gives me an error:
```
Module not found: Error: Can't resolve 'vue-chartjs' in <component name>
```
Note that when I tried to remove it and keep the import of `chart.js`, the error disappeared, which suggests that it has to do with the import statement of `vue-chartjs`
My repo is CommonJS, in case that matters

### Reproduction

I don't know the exact steps. The repo is my website which I'd like to keep private

### chart.js version

3.7.1

### vue-chartjs version

5.1.0

**Comment by drewzb** [comment] 2022-12-27 07:24
I'm having the same problem.

**Comment by dangreen** [comment] 2023-01-05 10:53
@avi12 @drewzb Hi. Please provide repo with minimal issue reproduction.

**Comment by kltb** [comment] 2023-01-05 11:16
I can imagine it's related to this:

"Chart.js becomes an [ESM-only package](https://nodejs.org/api/esm.html) ([the UMD bundle is still available](https://www.chartjs.org/docs/latest/getting-started/installation.html#cdn)). To use Chart.js, your project should also be an ES module. Make sure to have this in your package.json"

```
{
  "type": "module"
}
```

https://www.chartjs.org/docs/latest/migration/v4-migration.html#general


Also I believe #990 is a duplicate of this one.

**Comment by dangreen** [comment] 2023-01-05 11:37
@kltb [v5.1](https://github.com/apertureless/vue-chartjs/releases/tag/v5.1.0) is with CommonJS support

**Comment by dangreen** [comment] 2023-01-09 21:59
@avi12 @drewzb Hi. Please try vue-chartjs v5.2.0

**Closed by dangreen** 2023-01-09 21:59 UTC
