### ISSUE TITLE
Stacked Bar/Line in Vue Project?

### ISSUE THREAD

**Issue by xXxcb** [apertureless/vue-chartjs#742] opened 2021-12-22 02:16 UTC
Is it possible to get the Stcked Bar Line Chart in a vue project? 

### Environment
![Screen Shot 2021-12-21 at 9 10 09 PM](https://user-images.githubusercontent.com/23020371/147023254-a5314d31-c405-4b66-b264-fe07462b3cf8.png)

- vue.js version: 2.6.14
- vue-chart.js version: 3.5.1
- chart.js version: 3.6.2
- npm version: 7.22.0

**Comment by apertureless** [comment] 2021-12-22 07:38
Duplicate of #741

**Closed by apertureless** 2021-12-22 07:38 UTC
