### ISSUE TITLE
Colors of dynamically added bars in bar graph are the default color instead of specified color

### ISSUE THREAD

**Issue by ron** [apertureless/vue-chartjs#42] opened 2017-02-22 14:16 UTC
### Expected Behavior
When I update the chartData of a barchart containing a dynamic number of bars and an array of backgroundColors I expect the added bars to have the background color specified in the array.

For example:
I have a graph with 2 bars and a backgroundColors array of ['orange','green'] it displays correctly. When I update the data and it contains 3 bars with ['orange','green','blue'] the last bar is not blue but the default grey color.

I'm using the reactiveProp mixin.

### Actual Behavior
The last bar is grey, not the color specified in the array.

### Environment
- OS: OSX
- NPM Version: 2.3.5

**Comment by apertureless** [comment] 2017-02-22 14:34
Confirmed.

It's because the mixin set's only the data in the watcher, not the whole dataset object.

Will be fixed in `2.3.6`

**Comment by ron** [comment] 2017-02-22 14:40
Nice.
Can you recommend a quickfix for me so I can fix this now? I tried to add a watcher on chartData but got stuck on updating the backgroundColors.

**Comment by apertureless** [comment] 2017-02-22 14:53
2.3.6 is now in npm. Just update the package. ;)

**Comment by ron** [comment] 2017-02-22 14:57
It works, many thanks!

**Closed** 2017-02-22 14:58 UTC
Labels: ⚠️️ bug
