### ISSUE TITLE
How to pass data as props to scatter

### ISSUE THREAD

**Issue by JVP3122** [apertureless/vue-chartjs#483] opened 2019-03-05 23:07 UTC
### Expected Behavior
Trying to pass data in the format noted to a ScatterPlot.js file and rendering the correct graph.

This is my ScatterChart.js file
```
import { Scatter, mixins } from 'vue-chartjs'
// const { reactiveProp, reactiveData } = mixins

export default {
  extends: Scatter,
  mixins: [mixins.reactiveProp, mixins.reactiveData],
  props: ['chartData', 'options'],
  data: () => ({
  }),
  watch: {
  },
  mounted () {
    // this.chartData is created in the mixin.
    // If you want to pass options please create a local options object
    this.renderChart(this.chartData, this.options)
    console.log('this.chartData', this.chartData)
  }
}

```
Assume the datasets are of the same form as in the example:
```
datasets: [{
  label: 'Scatter Dataset 1',
  fill: false,
  borderColor: '#f87979',
  backgroundColor: '#f87979',
  data: [{
    x: -2,
    y: 4
  }, {
    x: -1,
    y: 1
  }, {
    x: 0,
    y: 0
  }, {
    x: 1,
    y: 1
  }, {
    x: 2,
    y: 4
  }]
},
  {
    label: 'Scatter Dataset 2',
    fill: false,
    borderColor: '#7acbf9',
    backgroundColor: '#7acbf9',
    data: [{
      x: -2,
      y: -4
    }, {
      x: -1,
      y: -1
    }, {
      x: 0,
      y: 1
    }, {
      x: 1,
      y: -1
    }, {
      x: 2,
      y: -4
    }]
  }]
```
I'm trying to pass the datasets to the separate chart file to render
### Actual Behavior
I get a message "TypeError: Cannot read property 'map' of undefined" and if I log chartData to the console I see an object with four entries:
```
0: {
  label: 'Scatter Dataset 1',
  fill: false,
  borderColor: '#f87979',
  backgroundColor: '#f87979',
  data: [{
    x: -2,
    y: 4
  }, {
    x: -1,
    y: 1
  }, {
    x: 0,
    y: 0
  }, {
    x: 1,
    y: 1
  }, {
    x: 2,
    y: 4
  }]
},
1: {
    label: 'Scatter Dataset 2',
    fill: false,
    borderColor: '#7acbf9',
    backgroundColor: '#7acbf9',
    data: [{
      x: -2,
      y: -4
    }, {
      x: -1,
      y: -1
    }, {
      x: 0,
      y: 1
    }, {
      x: 1,
      y: -1
    }, {
      x: 2,
      y: -4
    }]
  },
datasets: [],
labels: []
```

I see from the example that it's easy enough to directly pass datasets to the renderChart method, but I'm not sure what I'm doing wrong regarding passing the data in as props.

### Environment
- vue.js version: 3.4.0
- vue-chart.js version: 3.3.2
- npm version: 6.4.1

**Comment by apertureless** [comment] 2019-03-06 08:46
Hey @JVP3122 
sorry that you have trouble with it.

First, in general you should choose either `reactiveProp` or `reactiveData` not both. This will not work, as the one creates a `chartData` prop, and the other a `chartData` data variable.

However, the `reactiveMixins` do not work with the scatter chart right now. 
Because the mixin is iterating and copying the datasets and data, but the scatter chart, which was released in Chart.js in a later point, has a very different structure for the data. 

If you want to make it reactive, you'll have to attach a watcher yourself and then trigger an `update()`

**Comment by JVP3122** [comment] 2019-03-06 16:25
Thank you for the notes, @apertureless 

All of that said, even when I remove the mixin (I was playing around with one or the other and forgot to remove them before posting) it's still doing the same thing when I try to pass props to this function.  As a matter of fact, if I declare the data as mentioned above as local data within the _data_ function the same behavior is exhibited.  I feel like there I must be having a brain-fart type moment because passing data to a scatter chart as a prop instead of declaring it within the renderChart method can't be this hard.

**Comment by JVP3122** [comment] 2019-03-06 19:12
As an aside, I've instead chosen to use a Line graph so I've solved the initial issue I'm having but I'm leaving this up because I'm curious about it.

**Comment by apertureless** [comment] 2019-03-07 08:44
Are you getting your data from an API ? If you, you have to make sure, that the data is there before rendering the chart.

A codepen / jsfiddle for reproduction would be nice.

**Closed** 2019-03-18 06:19 UTC
Labels: ❓ question
