### ISSUE TITLE
[Bug]: Can't modify default options with nuxt

### ISSUE THREAD

**Issue by NekiKulLik** [apertureless/vue-chartjs#823] opened 2022-04-24 16:07 UTC
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

On latest Nuxt v2.15.8 version I have plugins file containing:
```
import Vue from "vue";
import { Line } from "vue-chartjs/legacy";
import {
  Chart as ChartJS,
  Title,
  Tooltip,
  Legend,
  BarElement,
  CategoryScale,
  LinearScale,
  LineElement,
  PointElement,
} from "chart.js";

ChartJS.register(
  Title,
  Tooltip,
  Legend,
  PointElement,
  BarElement,
  CategoryScale,
  LinearScale,
  LineElement,
);

Vue.component("line-chart", {
  extends: Line,
});
```

Then in **nuxt.config.js**:
`plugins: [
	{src: '~/plugins/chart.js', mode: 'client', ssr: false}
]`

And then I use it in a component with:
```
<template>
  <div>
    <client-only placeholder="Loading...">
      <line-chart
        :chart-options="options"
        :chart-data="data"
        :height="100"
        :width="300"
        chart-id="lineChart"
      />
    </client-only>
  </div>
</template>
```

But whatever I pass as options, such as `{ legend: {display: false} }` it won't hide the legend. Other options seem not to be working either for me. When I check with Vue Devtools extension, the props are passed in correctly to line-chart component. Am I missing something?

### Reproduction

https://codesandbox.io/s/fancy-forest-wf2i48?file=/pages/index.vue

### chart.js version

v3.7.1

### vue-chartjs version

v4.0.6

**Comment by apertureless** [comment] 2022-04-25 08:46
https://www.chartjs.org/docs/latest/configuration/legend.html#example

Looks like your options object is not right.

**Comment by Stacker8** [comment] 2022-05-20 11:50
> https://www.chartjs.org/docs/latest/configuration/legend.html#example
> 
> Looks like your options object is not right.
> 
> ```js
>  options: {
>         plugins: {
>           legend: {
>             display: false,
>           },
>         }
>       },
> ```

I have the same problem and that won't fix it

**Comment by apertureless** [comment] 2022-05-20 14:10
@Stacker8 Then your options object is maybe wrong too.
Passing legend under plugins key, worked as I tested it in the codesandbox.

But without having a reproduction, its hard to help you.
Check out the official docs https://www.chartjs.org/docs/latest/configuration/ on how configuration works and how to structure your options object.

If some options are working but others are not, its a good indicator that your options obejct is simply wrong.
Also note, that we don't do any fancy stuff with your options. We are just passing them to Chart.js.

**Closed** 2022-06-08 11:31 UTC
