### ISSUE TITLE
clean install of from npm cannot be used in gulp / browserify

### ISSUE THREAD

**Issue by apge-Jeremy** [apertureless/vue-chartjs#174] opened 2017-08-16 19:45 UTC
### Expected Behavior

i should be able to `npm install --save vue-chartjs`
then `const Bar = require('vue-chartjs').Bar;` in my modules, and my gulp/browserify build should work as normal.

### Actual Behavior

Babel (which is not used anywhere in my project) begins to throw errors on build. I think it is possible that a post install step is not being hit because it is attempting to build the module in browserify rather than just require it.

`{ ReferenceError: [BABEL] C:\GIT Projects\atlas-ui\node_modules\vue-chartjs\dist\vue-chartjs.js: Unknown option: C:\GIT Projects\atlas-ui\node_modules\vue-chartjs\package.json.presets while parsing file: C:\GIT Projects\atlas-ui\node_modules\vue-chartjs\dist\vue-chartjs.js
    at Logger.error (C:\GIT Projects\atlas-ui\node_modules\babelify\node_modules\babel-core\lib\transformation\file\logger.js:58:11)
    at OptionManager.mergeOptions (C:\GIT Projects\atlas-ui\node_modules\babelify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:126:29)
    at OptionManager.addConfig (C:\GIT Projects\atlas-ui\node_modules\babelify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:107:10)
    at OptionManager.findConfigs (C:\GIT Projects\atlas-ui\node_modules\babelify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (C:\GIT Projects\atlas-ui\node_modules\babelify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (C:\GIT Projects\atlas-ui\node_modules\babelify\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (C:\GIT Projects\atlas-ui\node_modules\babelify\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (C:\GIT Projects\atlas-ui\node_modules\babelify\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at Babelify._flush (C:\GIT Projects\atlas-ui\node_modules\babelify\index.js:27:22)
    at Babelify.<anonymous> (_stream_transform.js:118:12)
  filename: 'C:\\GIT Projects\\atlas-ui\\node_modules\\vue-chartjs\\dist\\vue-chartjs.js',
  stream: `

### Environment
- vue.js version: 2.3.3
- vue-chart.js version: 2.8.2
- npm version: 4.1.2
- node version 7.5.0

**Comment by apertureless** [comment] 2017-08-17 08:06
This could be related to this https://github.com/apertureless/vue-chartjs/blob/develop/package.json#L139-L143 which was added with https://github.com/apertureless/vue-chartjs/pull/51

To be honest, I can't really remember why it was added 🙈  The structure and build output changed over time. So they may were reasons back then. 

But I don't think it is really needed anymore.

**Comment by apertureless** [comment] 2017-08-22 08:59
@apge-Jeremy 

Are you using the vue-cli tempalte ? Or do you have a custom build pipeline? 
I need to reproduce it to check if it will be fixed, if I remove the babelify stuff from package.json

**Comment by apertureless** [comment] 2017-09-02 12:34
close due to inactivity

**Closed by apertureless** 2017-09-02 12:34 UTC
Labels: Need Repo
