### ISSUE TITLE
Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders

### ISSUE THREAD

**Issue by afuno** [apertureless/vue-chartjs#151] opened 2017-07-20 13:14 UTC
### Expected Behavior

The values in the chart should be changed without any errors.

I mean this code: http://vue-chartjs.org/#/home?id=reactive-data

### Actual Behavior

The chart is initialized. The values are displayed. After pressing the button, the values change.

But in the logs of the browser, this errors always appears:

> [Vue warn]: $attrs is readonly.

And second:

> [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "chartData"

My code is exactly the same as your code in the documentation. I did not specifically change it.

### Environment
- vue.js version: 2.4.1
- vue-chart.js version: 2.7.1
- npm version: 5.3.0 (but I use yarn)
- yarn version: 0.27.5

**Comment by afuno** [comment] 2017-07-20 13:20
If I replace this line:

```html
<line-chart :chart-data="datacollection"></line-chart>
```

On this line:

```html
<line-chart :chart-data="datacollection" :options="{ responsive: true, maintainAspectRatio: false }"></line-chart>
```

Then in the logs of the browser I get a second error:

> [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "options"

**Comment by apertureless** [comment] 2017-07-20 13:48
Can you please provide a codepen for reproduction?

**Comment by afuno** [comment] 2017-07-20 14:10
@apertureless I updated all the packages to the current versions. Now there is another error. I updated my first post.

> Can you please provide a codepen for reproduction?

I'm using the latest versions. I only use your code. You can perfectly reproduce the problem in yourself. Please.

**Comment by DenisLapi** [comment] 2017-07-20 18:01
@afuno This is how you can create a component without creating a new `.vue` file. This works on Codepen

```
Vue.component('my-component', {
  template: '<span>{{ message }}</span>',
  data: {
    message: 'hello'
  }
})
```

**Comment by afuno** [comment] 2017-07-20 20:12
@DenisLapi I do not need to create components this way. I use .vue components in the project. The question concerns only .vue files.

The author wrote the code in their documentation, which is not working properly.

**Comment by DenisLapi** [comment] 2017-07-20 20:16
@afuno I just wanted to show you how to create a component on Codepen, that was actually answer on your question/confusion how to create it. 
>P.S. I do not know how to demonstrate the .vue component on the codepen
Peace!

**Comment by someother1** [comment] 2017-07-21 06:16
https://github.com/vuejs/vue/releases/tag/v2.4.0 ($attrs is a new feature of vue).
downgrading vue to 2.3.4 works, until you deliver a patch.

**Comment by afuno** [comment] 2017-07-21 12:16
@someother1 This doesn't correct the main problem.

**Comment by claide** [comment] 2017-07-21 12:34
How about adding the options directly on your chartRender function, instead of using the :options.

**Comment by apertureless** [comment] 2017-07-22 16:05
Well thats weird.  I have the reactive prop example here in this repo
https://github.com/apertureless/vue-chartjs/blob/develop/src/examples/ReactivePropExample.js

And running here `yarn dev` works perfectly and the example chart is updating without any warnings.

And the mutating warning for the options is also weird. As the options never get mutated at any point.

Can you check out this repo and see if `yarn dev` works for you and you get any errors? 
You are using webpack right?

I will check for the `$attrs` warning. Right now the peerDependency is  `"vue": "^2.3.4"` I will update it to the latest vue version and see. 

However... it is also very weird... because as `attrs` are new in the latest vue release... I am not using it :o

**Comment by apertureless** [comment] 2017-07-22 16:27
Okay, I updated the peerDependency to match the current vue version.
But... I don't get the `$attrs` warning.

Any other have this warning?

**Comment by afuno** [comment] 2017-07-22 21:28
@apertureless I will write for the time being only about `$attrs`. This error only occurs when using your package. I do not know why it is so. But as soon as I removed the use of your package, all the bug is lost.

:(

**Comment by apertureless** [comment] 2017-07-23 07:08
Hm, thats interesting. Well that are only warnings. What is your build setup? Webpack 2?

**Comment by afuno** [comment] 2017-07-23 11:04
@apertureless Yes. https://github.com/rails/webpacker

**Comment by Mooooooon** [comment] 2017-07-29 20:20
@apertureless  Hi, I had the same Issues
This is my code

chart.js
```
import { Line, mixins } from 'vue-chartjs'
const {reactiveProp} = mixins

export default Line.extend({
  mixins: [reactiveProp],
  mounted () {
    this.renderChart(this.chartData, {
      //some options
    })
  }
})
```
chart.vue

```
<chart :chart-data="chartData"></chart>
<button @click="fillData()">Randomize</button>
```
```
import Chart from './chart/Chart'

export default {
  components: {Chart},
  data () {
    return {
      chartData: {
        labels: new Array(3),
        datasets: [{
          label: 'prices',
          data: [1, 2, 3]
        }]
      }
    }
  },
  methods: {
    fillData () {
      this.chartData = {
        labels: new Array(3),
        datasets: [
          {
            label: 'prices',
            data: [3, 2, 1]
          }
        ]
      }
    }
  }
}
```
It's similar to Example [http://vue-chartjs.org/#/home?id=reactive-data](http://vue-chartjs.org/#/home?id=reactive-data)

It works, but has some warning.

`[Vue warn]: $attrs is readonly.`

and

`[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "chartData"`

My package.json
```
"dependencies": {
  "chart.js": "^2.6.0",
  "element-ui": "^1.4.0",
  "normalize.css": "^7.0.0",
  "vue": "^2.3.3",
  "vue-chartjs": "^2.7.2",
  "vue-electron": "^1.0.6",
  "vue-router": "^2.5.3"
}
```

**Comment by Mooooooon** [comment] 2017-07-30 10:59
New findings.

The actual version is Vue 2.4
```
// yarn.lock 
vue@^2.3.3:
  version "2.4.2"
```
If I add some props(width or height) and do some operations(example: change v-model data), there will be warnings.
```
<chart :height="chartHeight" :width="chartWidth"></chart>
<input v-model="a">
```
```
data() {
  return {
    chartHeight: 200,
    chartWidth: 200,
    a: 1
  }
}
```
```
[Vue warn]: $attrs is readonly.
```

After removing the props, the warning disappears.

`<chart></chart>`

**Comment by apertureless** [comment] 2017-07-31 19:44
Can you create a minimal repository for reproduction? Right now with a clean vue cli scaffold, I can not reproduce it.

**Comment by Mooooooon** [comment] 2017-08-01 03:23
@apertureless You are right
I use `vue init simulatedgreg/electron-vue my-project`
Maybe you can closed this, I'm not sure what's wrong,

**Comment by farefray** [comment] 2017-08-08 08:30
I had exactly the same problem, but its gone after I upgraded vue from 2.2.2 to 2.4.2

**Comment by hambos22** [comment] 2017-08-14 16:57
+1 same issue here with the latest version of Vue

**Comment by apertureless** [comment] 2017-08-14 17:18
Hey @farefray , @hambos22 

did you scaffolded the project with vue-cli ? Which template?

**Comment by jenslind** [comment] 2017-08-14 22:05
@apertureless I think i'm running into this too.

Made a small repo to reproduce:
https://github.com/jenslind/vue-chartjs-151
`npm install && npm run build && open index.html`

It might be me doing something wrong too :cat:

**Comment by apertureless** [comment] 2017-08-15 08:11
Thanks @jenslind !

Will look into this.

**Comment by hambos22** [comment] 2017-08-15 09:11
Hello @apertureless. First of all I forgot to thank you for this very useful project! Great work!

I didn't scaffold with vue-cli. I'm having this issue with vanilla laravel installation.

**Comment by apertureless** [comment] 2017-08-15 09:39
@hambos22 okay thanks for the info. I will check it out.
You're using laravel mix to bundle it, right?

**Comment by hambos22** [comment] 2017-08-15 10:00
Yes exactly

**Comment by s0up** [comment] 2017-08-17 02:34
I seem to be having this issue as well using vue-chartjs@2.8.2 / vue@2.4.2 in my electron app. I'm literally using the same chart code and same vue/vue-chartjs versions on the non electron version and i get no errors.  Not sure what to make of that!

**Comment by karlpablo** [comment] 2017-08-17 21:49
I see the same issue on vue@2.4.2 and vue-chartjs@2.8.2. I fixed it by not rendering the donut component yet (v-if) until the donut data is ready.

**Comment by apertureless** [comment] 2017-08-22 08:56
I will check the electron boilerplate if I find some time.

**Comment by danieldocki** [comment] 2017-08-24 18:33
I'm having a similar problem, I use rails with the gem webpacker, it seems like it makes use of two instances of Vue.

![screen shot 2017-08-24 at 3 33 02 pm](https://user-images.githubusercontent.com/10542/29682498-9bd6595e-88e1-11e7-8195-0334aadfa6fa.png)

**Comment by apertureless** [comment] 2017-08-24 19:41
Are you using webpack 1 or 2?

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by s0up** [comment] 2017-08-24 20:29
I am currently using Webpack 2.  The app I'm having issues with was deployed via https://github.com/SimulatedGREG/electron-vue

**Comment by danieldocki** [comment] 2017-08-24 21:00
```
.
.
.
    "webpack": "^3.5.5",
    "webpack-manifest-plugin": "^1.1.0",
    "webpack-merge": "^4.1.0"
  },
  "devDependencies": {
    "webpack-dev-server": "^2.4.5"
  }
```

**Comment by zxc23** [comment] 2017-09-02 07:50
I'm currently getting this warning as well. I'm also using the electron-vue project at https://github.com/SimulatedGREG/electron-vue. I've made a wrapper component similar to that used by Vuestic-Admin at https://github.com/epicmaxco/vuestic-admin

```[Vue warn]: $attrs is readonly.

[Vue warn]: Avoid mutating a prop directly since the value will be overwritten
```

The warnings show up whenever the data changes. Everything appears to work correctly, it's just console warnings at the moment. I will continue trying to solve this.

**Comment by apertureless** [comment] 2017-09-16 12:31
Well this seems to be related to electron. However I am not sure why... and it only appears if you're using the bundled version.

**Comment by apertureless** [comment] 2017-09-16 12:45
Okay, I am still not sure, why. But it seems that electron does not like the `extend()` 

However you could also use the extend in the component or as a mixin.

```js
<script>
import {Line, mixins} from 'vue-chartjs'
const {reactiveProp} = mixins

export default {
  mixins: [reactiveProp, Line],
  mounted () {
    this.renderChart(this.chartData, {responsive: true, maintainAspectRatio: false})
  }
}
</script>

```

This way no warnings get thrown.

**Closed** 2017-09-16 12:49 UTC
Labels: Need Repo, ✍ help wanted

**Comment by zxc23** [comment] 2017-09-16 14:29
Thanks. That does prevent the warnings. Strange issue.
