### ISSUE TITLE
LIB_VERSION is not defined

### ISSUE THREAD

**Issue by Laruxo** [apertureless/vue-chartjs#310] opened 2018-02-11 21:39 UTC
With 3.2 release I see that you added LIB_VERSION constant that you resolve with webpack.

However when using webpack 2 to build my project I also have to define this constant or revert code changes in `es/index.js`.
Without that, I get `ReferenceError: LIB_VERSION is not defined`

I think this package should work without modifications like this.

**Comment by t202wes** [comment] 2018-02-11 22:15
Having the same error.

**Comment by markers16123** [comment] 2018-02-12 04:43
I get the same error as following on windows 10. (note that is working good on the osx.)
> index.js?5253:4 Uncaught ReferenceError: LIB_VERSION is not defined
    at eval (index.js?5253:4)
    at Object../node_modules/vue-chartjs/es/index.js (app.js:2903)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (selector.js?type=script&index=0!./src/components/Update/Dashboard/VersionChart.vue:1)
    at Object../node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Update/Dashboard/VersionChart.vue (app.js:1045)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (VersionChart.vue?139a:1)
    at Object../src/components/Update/Dashboard/VersionChart.vue (app.js:3412)

**Comment by faustbrian** [comment] 2018-02-12 04:57
Looks like it is related to this PR https://github.com/apertureless/vue-chartjs/pull/305.

https://github.com/apertureless/vue-chartjs/pull/305/files#diff-e4403a877d80de653400d88d85e4801aR20
https://github.com/apertureless/vue-chartjs/pull/305/files#diff-8dc8796144fc0bf0dc97a14a920bbe66R80

**Comment by markers16123** [comment] 2018-02-12 05:31
I tried version 3.1.0 but the error still occurs.
>   "dependencies": {
    "axios": "^0.17.1",
    "chart.js": "^2.7.1",
    "es6-promise": "^4.2.3",
    "vue": "^2.5.2",
    "vue-chartjs": "^3.1.0",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },

**Comment by faustbrian** [comment] 2018-02-12 05:32
Your version constraint pulls in everything that matches 3.1.0 or higher. You need to specifically require `"vue-chartjs": "3.1.0"`.

**Comment by markers16123** [comment] 2018-02-12 05:57
Thanks a lot. It works perfectly.
Do you know if I should continue to use this version?
Or, can I use the latest version in the future?

**Comment by faustbrian** [comment] 2018-02-12 05:59
The error is currently caused by the build process with Webpack so once that is fixed you should be able to pull in `^3.2.0`.

For now just use `3.1.0` and wait for a fix.

**Comment by markers16123** [comment] 2018-02-12 06:03
Okay. I understood everything.
Thanks.

**Comment by pesama** [comment] 2018-02-12 10:42
Same error happening here. Dwgrading to 3.1.0 worked.

**Comment by apertureless** [comment] 2018-02-12 10:53
Sorry for that.
It's fixed now in 3.2.1

**Closed** 2018-02-12 10:56 UTC
Labels: ⚠️️ bug
