### ISSUE TITLE
maintainAspectRatio is not work

### ISSUE THREAD

**Issue by essivision** [apertureless/vue-chartjs#534] opened 2019-07-09 11:51 UTC
### Expected Behavior
I need to set `maintainAspectRatio` to `false`. but I see chart aspectRatio as `true`. I need chart as rectangle. I use this code:
```
<script>
    import { Bar, mixins } from 'vue-chartjs'

    export default {
        extends: Bar,
        mixins: [mixins.reactiveProp],
        props: ['chartData', 'title'],
        mounted () {
            this.options = {
                responsive: true,
                maintainAspectRatio: false,
                title: {
                    display: true,
                    text: this.title
                },
                tooltips: {
                    mode: 'index',
                        intersect: false
                },
                scales: {
                    xAxes: [{
                        stacked: true
                    }],
                        yAxes: [{
                        stacked: true
                    }]
                }
            };

            this.renderChart(this.chartData, this.options)
        }
    }
</script>
```
but see this chart :
![image](https://user-images.githubusercontent.com/7271330/60885738-877ca400-a265-11e9-9430-30c494782fe7.png)

what should I do? 

### Environment
- vue.js version: 2.5.*
- vue-chart.js version: 3.4.2
- npm version: 6.4.1

**Comment by apertureless** [comment] 2019-07-09 12:10
Well, your code is faulty. 

You are defining `options` as a prop. Which in general is **read-only** and should not be mutated.

Then in your mounted hook for what ever reasons you are setting your options and mutating your prop.

You should define `options` as a `data()` model.

**Comment by essivision** [comment] 2019-07-09 12:19
I change it. Okay. 
But when I used it with `v-if` it doesn't work like below code. I means `maintainAspectRatio` doesn't work and show chart as Square.
```
           <template v-if="chartType === 'bar'">
                <bar-chart
                        title="title"
                        :chart-data="chartData">
                </bar-chart>
            </template>
```

**Comment by apertureless** [comment] 2019-07-09 12:42
I guess this is a duplicate of #503

**Closed** 2020-08-28 14:08 UTC
Labels: duplicate, ❓ question
